name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: npm run-script test:unit

      - name: Run visual regression tests on PR
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: npm run-script test:visual
