name: Unit Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    permissions:
      contents: write
      pull-requests: write
    uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/workflows/unit-and-vrt-tests.yml@main
