name: Update Screenshots

on: [push, workflow_dispatch]

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    container: docker://mcr.microsoft.com/playwright:v1.53.0-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-node-env

      - name: Run visual regression tests
        run: npm run test:visual
        id: tests
        continue-on-error: true

      - name: Update screenshots
        if: ${{ steps.tests.outcome == 'failure' }}
        env:
          HOME: /root
        run: |
          npm run test:update
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add screenshots
          git commit -m "test: update screenshots"
          git push
